Repository Klynger/genus-client, pull requests merged in 2018-10, with the labels that each got.

#67 Fix/user dropdown
  src/components/Home/ApplicationBar.js
  src/components/Home/UserMenu.js
Labels: UX, bug

#71 Add breakpoints to GradeDetailsPage component container
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/index.js
  src/components/utils/SharedComponents.js
Labels: UX, bug

#73 Fix layout problem + remove select
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/SubjectGrid.js
  src/components/InstitutionPage/SubjectCreateDialog.js
  src/components/utils/helpers.js
Labels: UX, bug, refactor

#75 Fix variant of typography
  src/components/utils/SharedComponents.js
  src/components/utils/theme.js
Labels: bug

#78 Refactor/grid cards
  src/components/InstitutionPage/DetailsPage/GradeCard.js
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/SubjectsGrid.js
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/index.js
  src/components/InstitutionPage/DetailsPage/GradesGrid.js
  src/components/InstitutionPage/GradeCreateDialog.js
  src/components/utils/GridCard.js
Labels: refactor

#80 Fix all typography variants that cause warning at institution details
  src/components/InstitutionPage/DetailsPage/EmployeeList.js
  src/components/InstitutionPage/DetailsPage/InstitutionInfo.js
  src/components/InstitutionPage/DetailsPage/index.js
Labels: refactor

#81 Refactor/add user to store
  src/actions/institution.js
  src/components/InstitutionPage/DetailsPage/index.js
  src/components/utils/helpers.js
  src/queryGenerators/institutionQueries.js
  src/reducers/grade.js
  src/reducers/institution.js
  src/reducers/subject.js
  src/reducers/user.js
Labels: enhancement, refactor

#83 add remove user dialog
  src/actions/actionTypes.js
  src/actions/institution.js
  src/actions/user.js
  src/components/InstitutionPage/DetailsPage/EmployeeList.js
  src/components/InstitutionPage/DetailsPage/RemoveUserDialog.js
  src/components/InstitutionPage/DetailsPage/index.js
  src/queryGenerators/institutionMutations.js
  src/queryGenerators/institutionQueries.js
  src/queryGenerators/userMutations.js
  src/reducers/institution.js
  src/reducers/user.js
Labels: enhancement

#86 refactor and fix RemoveUserDialog component
  src/actions/user.js
  src/components/InstitutionPage/DetailsPage/EmployeeList.js
  src/components/InstitutionPage/DetailsPage/RemoveUserDialog.js
  src/components/InstitutionPage/DetailsPage/index.js
  src/reducers/institution.js
Labels: bug, refactor

#95 Feature/update dependencies
  package.json
  src/components/App/index.js
Labels: enhancement

#100 Rename EmployeeList to UserList and add students to institution details
  src/actions/institution.js
  src/components/InstitutionPage/DetailsPage/UserList.js
  src/components/InstitutionPage/DetailsPage/index.js
  src/components/TestingPage/index.js
  src/queryGenerators/institutionMutations.js
  src/queryGenerators/institutionQueries.js
Labels: enhancement

#102 Feature/user page
  src/actions/user.js
  src/components/Home/HomeLoading.js
  src/components/Home/HomeRoutes.js
  src/components/Home/UserMenu.js
  src/components/UserPage/ProfileDetailsPage/EditUserDialog.js
  src/components/UserPage/ProfileDetailsPage/UserInfo.js
  src/components/UserPage/ProfileDetailsPage/index.js
  src/components/UserPage/UserLoading.js
  src/components/UserPage/UserRoutes.js
  src/components/UserPage/index.js
  src/components/utils/ImageUploader.js
  src/components/utils/ProgressButton.js
  src/components/utils/helpers.js
  src/queryGenerators/userMutations.js
  src/queryGenerators/userQueries.js
  src/reducers/user.js
Labels: enhancement

#105 Feature/edit institution
  src/actions/actionTypes.js
  src/actions/institution.js
  src/components/InstitutionPage/DetailsPage/EditInstitutionDialog.js
  src/components/InstitutionPage/DetailsPage/InstitutionInfo.js
  src/components/InstitutionPage/DetailsPage/RemoveUserDialog.js
  src/components/InstitutionPage/DetailsPage/index.js
  src/queryGenerators/institutionMutations.js
  src/reducers/institution.js
Labels: enhancement

#107 Feature/edit subject
  src/actions/actionTypes.js
  src/actions/subject.js
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/SubjectDetailsPage/EditSubjectDialog.js
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/SubjectDetailsPage/SubjectInfo.js
  src/components/InstitutionPage/DetailsPage/GradePage/GradeDetailsPage/SubjectDetailsPage/index.js
  src/queryGenerators/SubjectMutations.js
  src/reducers/subject.js
Labels: enhancement
