Repository Klynger/genus-client, pull requests merged in 2018-11, with the labels that each got.

#110 remove empty lines at .eslintignore and fixed prettier errors
  .eslintignore
  .eslintrc.js
  .eslintrc.spellcheck.js
Labels: bug, config

#111 Feature/edit password
  src/components/UserPage/ProfileDetailsPage/EditPasswordDialog.js
  src/components/UserPage/ProfileDetailsPage/UserInfo.js
  src/components/UserPage/ProfileDetailsPage/index.js
  src/queryGenerators/userMutations.js
Labels: enhancement

#117 Add react-markdown dependency and Add DiscussionCard component layout
  package.json
  src/components/Forum/ForumDiscussionsPage/DiscussionCard.js
  src/components/TestingPage/index.js
Labels: enhancement

#118 Feature/add student subject
  src/actions/actionTypes.js
  src/actions/institution.js
  src/actions/subject.js
  src/components/Subject/SubjectDetails/AddStudentDialog.js
  src/components/Subject/SubjectDetails/SubjectInfo.js
  src/components/Subject/SubjectDetails/index.js
  src/queryGenerators/SubjectMutations.js
  src/queryGenerators/institutionMutations.js
  src/queryGenerators/institutionQueries.js
  src/reducers/subject.js
Labels: enhancement

#120 add route to Discussion
  src/components/Forum/Discussion/DiscussionCard.js
  src/components/Forum/Discussion/index.js
  src/components/TestingPage/TestingRoutes.js
  src/components/TestingPage/index.js
Labels: enhancement

#126 Hot fix add forum to create subject mutation
  src/queryGenerators/SubjectMutations.js
Labels: bug

#128 hot fix create discussion and access discussion page
  src/actions/discussion.js
  src/components/Subject/SubjectDetails/AddStudentDialog.js
Labels: bug

#130 Refactor/default route container
  src/components/Forum/Discussion/index.js
  src/components/Forum/ForumDiscussions/index.js
  src/components/Forum/NewDiscussion/NewDiscussionForm.js
  src/components/Forum/NewDiscussion/index.js
  src/components/Grade/GradeDetails/index.js
  src/components/Home/HomeRoutes.js
  src/components/Home/index.js
  src/components/Institution/CreateInstitution/InstitutionForm.js
  src/components/Institution/CreateInstitution/index.js
  src/components/Institution/EntryCode/AssociateDialog.js
  src/components/Institution/EntryCode/CreateEntryCodeDialog.js
  src/components/Institution/GradeCreateDialog.js
  src/components/Institution/InstitutionDetails/EditInstitutionDialog.js
  src/components/Institution/InstitutionDetails/RemoveUserDialog.js
  src/components/Institution/InstitutionDetails/index.js
  src/components/Institution/SubjectCreateDialog.js
  src/components/Institution/index.js
  src/components/Landing/Signin.js
  src/components/Landing/Signup.js
  src/components/Subject/SubjectDetails/AddStudentDialog.js
  src/components/Subject/SubjectDetails/AddTeacherDialog.js
  src/components/Subject/SubjectDetails/index.js
  src/components/Testing/TestingRoutes.js
  src/components/Testing/index.js
  src/components/TestingPage/index.js
  src/components/User/ProfileDetails/EditPasswordDialog.js
  src/components/User/ProfileDetails/EditUserDialog.js
  src/components/User/ProfileDetails/index.js
  src/components/UserPage/ProfileDetailsPage/EditPasswordDialog.js
  src/components/utils/DefaultContainerRoute.js
  src/components/utils/SharedComponents.js
Labels: refactor

#133 Refactor/add normalizr
  package.json
  src/actions/discussion.js
  src/actions/grade.js
  src/actions/institution.js
  src/actions/subject.js
  src/components/Forum/Discussion/DiscussionCard.js
  src/components/Forum/Discussion/index.js
  src/components/Grade/GradeDetails/SubjectsGrid.js
  src/components/Grade/GradeDetails/index.js
  src/components/Institution/InstitutionDetails/GradesGrid.js
  src/components/utils/DefaultContainerRoute.js
  src/components/utils/helpers.js
  src/models/schema.js
  src/queryGenerators/GradeMutations.js
  src/queryGenerators/GradeQueries.js
  src/queryGenerators/SubjectMutations.js
  src/queryGenerators/discussionMutations.js
  src/queryGenerators/institutionMutations.js
  src/queryGenerators/institutionQueries.js
Labels: refactor

#135 Add graphql fragments and graphql.macro to use .graphql files
  package.json
  src/actions/user.js
  src/components/Institution/EntryCode/CreateEntryCodeDialog.js
  src/queryGenerators/GradeMutations.js
  src/queryGenerators/GradeQueries.js
  src/queryGenerators/SubjectMutations.js
  src/queryGenerators/discussionMutations.js
  src/queryGenerators/entryCodeMutations.js
  src/queryGenerators/graphql/discussion/createDiscussion.graphql
  src/queryGenerators/graphql/discussion/discussionFragment.graphql
  src/queryGenerators/graphql/grade/createGrade.graphql
  src/queryGenerators/graphql/grade/findGrade.graphql
  src/queryGenerators/graphql/grade/gradeFragment.graphql
  src/queryGenerators/graphql/institution/createEntryCode.graphql
  src/queryGenerators/graphql/institution/createInstitution.graphql
  src/queryGenerators/graphql/institution/getInstitutionFragment.graphql
  src/queryGenerators/graphql/institution/getInstitutionsFromLoggedUser.graphql
  src/queryGenerators/graphql/institution/institutionFragment.graphql
  src/queryGenerators/graphql/institution/joinInstitution.graphql
  src/queryGenerators/graphql/institution/updateInstitution.graphql
  src/queryGenerators/graphql/reply/replyFragment.graphql
  src/queryGenerators/graphql/subject/addStudentToSubject.graphql
  src/queryGenerators/graphql/subject/addTeacherToSubject.graphql
  src/queryGenerators/graphql/subject/createSubject.graphql
  src/queryGenerators/graphql/subject/subjectFragment.graphql
  src/queryGenerators/graphql/subject/updateSubject.graphql
  src/queryGenerators/graphql/user/createUser.graphql
  src/queryGenerators/graphql/user/findLoggedUser.graphql
  src/queryGenerators/graphql/user/findUser.graphql
  src/queryGenerators/graphql/user/login.graphql
  src/queryGenerators/graphql/user/removeUserFromInstitution.graphql
  src/queryGenerators/graphql/user/updateUser.graphql
  src/queryGenerators/graphql/user/updateUserPassword.graphql
  src/queryGenerators/graphql/user/userFragment.graphql
  src/queryGenerators/institutionMutations.js
  src/queryGenerators/institutionQueries.js
  src/queryGenerators/userMutations.js
  src/queryGenerators/userQueries.js
Labels: enhancement, refactor

#136 Refactor/utils
  src/actions/discussion.js
  src/actions/grade.js
  src/actions/institution.js
  src/actions/subject.js
  src/actions/user.js
  src/components/App/Routes.js
  src/components/App/index.js
  src/components/Forum/Discussion/DiscussionCard.js
  src/components/Forum/Discussion/index.js
  src/components/Forum/ForumDiscussions/DiscussionCard.js
  src/components/Forum/ForumDiscussions/DiscussionItem.js
  src/components/Forum/ForumDiscussions/index.js
  src/components/Forum/NewDiscussion/NewDiscussionForm.js
  src/components/Forum/NewDiscussion/index.js
  src/components/Grade/GradeDetails/SubjectsGrid.js
  src/components/Grade/GradeDetails/index.js
  src/components/Institution/CreateGradeDialog.js
  src/components/Institution/CreateInstitution/index.js
  src/components/Institution/CreateSubjectDialog.js
  src/components/Institution/EntryCode/AssociateDialog.js
  src/components/Institution/EntryCode/CreateEntryCodeDialog.js
  src/components/Institution/EntryCode/DisplayCodeDialog.js
  src/components/Institution/InstitutionDetails/EditInstitutionDialog.js
  src/components/Institution/InstitutionDetails/GradesGrid.js
  src/components/Institution/InstitutionDetails/InstitutionInfo.js
  src/components/Institution/InstitutionDetails/RemoveUserDialog.js
  src/components/Institution/InstitutionDetails/SubjectDialog.js
  src/components/Institution/InstitutionDetails/index.js
  src/components/Landing/Signin.js
  src/components/Landing/Signup.js
  src/components/Landing/index.js
  src/components/Subject/SubjectDetails/AddStudentDialog.js
  src/components/Subject/SubjectDetails/AddTeacherDialog.js
  src/components/Subject/SubjectDetails/EditSubjectDialog.js
  src/components/Subject/SubjectDetails/SubjectInfo.js
  src/components/Subject/SubjectDetails/index.js
  src/components/User/ProfileDetails/EditPasswordDialog.js
  src/components/User/ProfileDetails/EditUserDialog.js
  src/components/User/ProfileDetails/UserInfo.js
  src/components/User/ProfileDetails/index.js
  src/components/shared/AuthRoute.js
  src/components/shared/DefaultContainerRoute.js
  src/components/shared/GridButton.js
  src/components/shared/GridCard.js
  src/components/shared/ImageUploader.js
  src/components/shared/ProgressButton.js
  src/components/shared/SharedComponents.js
  src/reducers/discussion.js
  src/reducers/grade.js
  src/reducers/institution.js
  src/reducers/reply.js
  src/reducers/subject.js
  src/reducers/user.js
  src/utils/HTTPClient.js
  src/utils/helpers.js
  src/utils/theme.js
Labels: refactor

#138 Feature/custom text field
  src/components/Institution/CreateInstitution/InstitutionForm.js
  src/components/Institution/CreateInstitution/index.js
  src/components/shared/CustomTextField.js
Labels: enhancement, refactor

#143 Feature/join institution rework
  src/components/Institution/EntryCode/CreateEntryCodeDialog.js
  src/components/Institution/EntryCode/GenerateCodeDialog.js
  src/components/Institution/InstitutionDetails/InstitutionInfo.js
  src/components/Institution/InstitutionDetails/InstitutionInfoMenu.js
  src/components/Institution/InstitutionDetails/index.js
  src/components/shared/CustomTextField.js
Labels: UX, bug, enhancement

#141 refactor signup component with new CustomTextField and user actions
  src/actions/user.js
  src/components/Institution/CreateInstitution/InstitutionForm.js
  src/components/Landing/Signup.js
  src/queryGenerators/graphql/user/createUser.graphql
Labels: enhancement, refactor

#145 fix graphql queries field names
  src/queryGenerators/graphql/discussion/discussionFragment.graphql
  src/queryGenerators/graphql/grade/findGrade.graphql
  src/queryGenerators/graphql/institution/getInstitutionsFromLoggedUser.graphql
  src/queryGenerators/graphql/reply/getReplyFragment.graphql
  src/queryGenerators/graphql/reply/replyFragment.graphql
Labels: bug

#149 Fix reply to reply error
  src/actions/reply.js
  src/components/Forum/Discussion/AddReply.js
  src/components/Forum/Discussion/DiscussionCard.js
  src/components/Forum/Discussion/ReplyCard.js
  src/components/Forum/Discussion/index.js
  src/models/schema.js
Labels: bug

#150 Fix problems when an user is not logged in
  src/actions/user.js
  src/components/Home/ApplicationBar.js
Labels: bug

#152 Feature/add multi subjects
  src/actions/actionTypes.js
  src/actions/subject.js
  src/components/Grade/GradeDetails/AddStudentToGradeDialog.js
  src/components/Grade/GradeDetails/GradeInfo.js
  src/components/Grade/GradeDetails/GradeInfoMenu.js
  src/components/Grade/GradeDetails/index.js
  src/components/Home/HomeRoutes.js
  src/components/Subject/SubjectDetails/index.js
  src/components/shared/AddUserDialogEmptyView.js
  src/components/shared/ProgressButton.js
  src/queryGenerators/SubjectMutations.js
  src/queryGenerators/graphql/subject/addStudentToSubjectsInGrade.graphql
  src/reducers/subject.js
Labels: enhancement
