Repository Klynger/genus-client, pull requests merged in 2019-03, with the labels that each got.

#165 Fix problems in the tables UI
  src/components/Institution/InstitutionDetails/UserList.js
Labels: UI, bug

#166 Fix/dialogs action disable
  package.json
  src/components/Grade/GradeDetails/GradeInfoMenu.js
  src/components/Institution/CreateGradeDialog.js
  src/components/Institution/CreateSubjectDialog.js
  src/components/Institution/EntryCode/AssociateDialog.js
  src/components/Institution/EntryCode/GenerateCodeDialog.js
  src/components/Institution/InstitutionDetails/EditInstitutionDialog.js
  src/components/Subject/SubjectDetails/AddStudentDialog.js
  src/components/shared/AuthRoute.js
Labels: UI, bug

#167 Feature/markdown editor
  package.json
  src/components/Forum/NewDiscussion/NewDiscussionForm.js
  src/components/shared/CustomMarkdownEditor.js
Labels: UX, enhancement, refactor

#182 Add default route that changes with the role of the user
  src/components/Home/HomeRoutes.js
  src/components/Home/index.js
  src/utils/constants.js
  src/utils/helpers.js
Labels: enhancement, refactor

#190 fix InstitutionInfoMenu position to be open
  src/components/Institution/InstitutionDetails/InstitutionInfoMenu.js
Labels: UI

#189 Fix/editor layout bugs
  src/components/Forum/Discussion/DiscussionCard.js
  src/components/shared/CustomMarkdownEditor.js
Labels: bug
