Repository Klynger/genus-client, pull requests merged in 2019-04, with the labels that each got.

#197 Fix showing add subject and add grade to users that cannot do this
  src/components/Grade/GradeDetails/SubjectsGrid.js
  src/components/Grade/GradeDetails/index.js
  src/components/Institution/InstitutionDetails/GradesGrid.js
Labels: bug, enhancement

#204 Fix EvaluationResult update
  src/actions/evaluationResult.js
  src/components/Subject/SubjectDetails/EditEvaluationDialog.js
  src/components/Subject/SubjectDetails/StudentsTable.js
  src/queryGenerators/evaluationResultMutations.js
  src/queryGenerators/graphql/evaluationResult/editEvaluationResult.graphql
  src/queryGenerators/graphql/evaluationResult/updateEvaluationResults.graphql
Labels: bug

#203 Feature/profile views
  src/components/User/ProfileDetails/CardDetail.js
  src/components/User/ProfileDetails/CardDetailsList.js
  src/components/User/ProfileDetails/UserInfo.js
  src/utils/helpers.js
Labels: enhancement

#205 Refresh page when adding student to grade + center text on studentsTable
  package.json
  src/components/Subject/SubjectDetails/AddStudentDialog.js
  src/components/Subject/SubjectDetails/StudentsTable.js
Labels: bug

#208 Feature/new image uploader
  package.json
  public/static/images/default_user_image.png
  src/components/Institution/CreateInstitution/InstitutionForm.js
  src/components/Landing/Signup.js
  src/components/Testing/TestingRoutes.js
  src/components/Testing/index.js
  src/components/User/ProfileDetails/EditUserDialog.js
  src/components/User/ProfileDetails/UserInfo.js
  src/components/shared/Image.js
  src/queryGenerators/graphql/user/updateUser.graphql
  src/queryGenerators/graphql/user/userFragment.graphql
  src/utils/constants.js
  src/utils/helpers.js
Labels: enhancement

#209 Pretty UI
  src/components/Home/DrawerContent.js
  src/components/Home/MenuDrawer.js
  src/components/Home/index.js
  src/components/Institution/InstitutionDetails/index.js
  src/components/Subject/SubjectDetails/SubjectInfo.js
  src/components/Subject/SubjectDetails/index.js
  src/components/User/ProfileDetails/CardDetailsList.js
  src/components/shared/SharedComponents.js
Labels: enhancement

#210 Fix send email to subject students
  src/components/Subject/SubjectDetails/index.js
Labels: bug

#211 Feature/entities image
  public/static/images/default_grade_image.jpg
  public/static/images/default_institution_image.png
  public/static/images/default_subject_image.jpeg
  src/actions/actionTypes.js
  src/actions/grade.js
  src/actions/subject.js
  src/components/Grade/GradeDetails/EditGradeDialog.js
  src/components/Grade/GradeDetails/GradeInfo.js
  src/components/Grade/GradeDetails/GradeInfoMenu.js
  src/components/Grade/GradeDetails/SubjectsGrid.js
  src/components/Grade/GradeDetails/index.js
  src/components/Institution/CreateInstitution/InstitutionForm.js
  src/components/Institution/InstitutionDetails/EditInstitutionDialog.js
  src/components/Institution/InstitutionDetails/GradesGrid.js
  src/components/Institution/InstitutionDetails/InstitutionInfo.js
  src/components/Institution/InstitutionDetails/UserList.js
  src/components/Subject/SubjectDetails/AddTeacherDialog.js
  src/components/Subject/SubjectDetails/EditSubjectDialog.js
  src/components/Subject/SubjectDetails/SubjectInfo.js
  src/components/Subject/SubjectDetails/index.js
  src/components/shared/GridCard.js
  src/components/shared/Image.js
  src/queryGenerators/GradeMutations.js
  src/queryGenerators/graphql/grade/gradeFragment.graphql
  src/queryGenerators/graphql/grade/updateGrade.graphql
  src/queryGenerators/graphql/institution/institutionFragment.graphql
  src/queryGenerators/graphql/subject/subjectFragment.graphql
  src/reducers/subject.js
  src/utils/constants.js
  src/utils/helpers.js
Labels: enhancement

#212 Fix/bug store table
  src/actions/actionTypes.js
  src/actions/evaluation.js
  src/components/Subject/SubjectDetails/AddGradeDialog.js
  src/components/Subject/SubjectDetails/index.js
  src/reducers/subject.js
Labels: bug

#216 Fix/subject email behavior
  src/components/Grade/GradeDetails/AddStudentToGradeDialog.js
  src/components/Subject/SubjectDetails/SubjectInfo.js
  src/components/Subject/SubjectDetails/index.js
Labels: bug
